// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFFm-Ini_q8EOTMmOjxFGp0k9x9FHQhx8',
    appId: '1:682470221138:web:ffacd5a3735aa66b1ec68b',
    messagingSenderId: '682470221138',
    projectId: 'jualan-lawe-lawe',
    authDomain: 'jualan-lawe-lawe.firebaseapp.com',
    databaseURL: 'https://jualan-lawe-lawe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jualan-lawe-lawe.appspot.com',
    measurementId: 'G-HZJ9LK47VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPP2mgfjR0_GJO5iw6DVSDNABMamKduXg',
    appId: '1:682470221138:android:b321e0ccc038c65f1ec68b',
    messagingSenderId: '682470221138',
    projectId: 'jualan-lawe-lawe',
    databaseURL: 'https://jualan-lawe-lawe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jualan-lawe-lawe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKydPkAapOGggyaegKNsfvs8g8UBjLU2A',
    appId: '1:682470221138:ios:2c6e0d4b86ab25a81ec68b',
    messagingSenderId: '682470221138',
    projectId: 'jualan-lawe-lawe',
    databaseURL: 'https://jualan-lawe-lawe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jualan-lawe-lawe.appspot.com',
    iosClientId: '682470221138-u0ail49nd67ag7mfh71ruunqdirh8n88.apps.googleusercontent.com',
    iosBundleId: 'com.example.jll',
  );
}
